repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: double-quote-string-fixer

-   repo: https://gitlab.com/PyCQA/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
