# Generated by Django 3.1.4 on 2020-12-06 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mentor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mentor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
    ]
