# Generated by Django 2.2.16 on 2020-12-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201206_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='keywords',
        ),
        migrations.AddField(
            model_name='question',
            name='keywords',
            field=models.ManyToManyField(related_name='questions', to='core.Keyword'),
        ),
    ]
