# Generated by Django 2.2.16 on 2020-12-07 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201206_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairsession',
            name='feedback_session',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pair_sessions', to='core.FeedbackForm'),
        ),
    ]
