# Generated by Django 2.2.16 on 2020-12-07 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201207_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairsession',
            name='feedback_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pair_sessions', to='core.FeedbackForm'),
        ),
    ]
