# Generated by Django 3.1.4 on 2020-12-08 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201207_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='core.degree'),
            preserve_default=False,
        ),
    ]
