# Generated by Django 2.2.16 on 2020-12-08 09:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_keyword_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.FloatField(default=0)),
                ('feedback_form', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.FeedbackForm')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.Mentor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.Student')),
            ],
            options={
                'default_related_name': 'appointments',
            },
        ),
    ]
