# Generated by Django 3.1.4 on 2020-12-08 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='core.degree'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='core.university'),
        ),
    ]
